### ISSUE TITLE
There is a typing error

### ISSUE THREAD

**Issue by soaresderik** [Apress/pro-vue-js-2#1]
https://github.com/Apress/pro-vue-js-2/blob/7633bb2a33166531ecf8f3237677c593934c2beb/05%20-%20SportsStore/sportsstore/src/components/PageControls.vue#L13

I think the author wanted to have typed 'btn-secondary'.

**Comment by orlovskyjavaprofi** [comment]
Still i gettting the same error Unhandled promise rejection Error: "Network Error"

**Comment by robwestbrook** [comment]
When I correct the class to`class= btn btn-secondary` the current page number loses the `btn-primary` class and color. With the misspelling everything works.

**Comment by AndreyGS** [comment]
`'btn-secpmdary'` is a misspelled class name. If you visit [bootstrap site](https://getbootstrap.com/docs/4.0/components/buttons/) you will see that there is no such class. And when you writes it no action is applied.

 So you can write `'btn btn-secpmdary'` or `'btn'` - it all will provide the same result. But if you write `'btn btn-secondary'` btn-secondary class will be applied to the current button. 

Actualy, here, all buttons will get the same btn-secondary class despite this 
`v-bind:class="{ 'btn-primary': i == currentPage }"`
instruction. It's because `'btn-primary'` class name not replacing `'btn-secondary'` class but joins to initial classes like `'btn btn-secondary btn-primary'` and in such case the last one class name `'btn-primary'` is not processed because `'btn-secondary'` class was applied before and all buttons getting respective 'secondary' look.

P.S.: [here, in 7'th chapter, in the same file PageControls.vue](https://github.com/Apress/pro-vue-js-2/blob/7633bb2a33166531ecf8f3237677c593934c2beb/07%20-%20SportsStore%20-%20Scaling%20and%20Administration/sportsstore/src/components/PageControls.vue) the same misspellings are present.
